spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: config-client
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      discovery:
        enabled: true  #开启从配置中心读取文件
        service-id: config-server  #指定配置中心的服务名
      label: master  #指明远程仓库的分支
      profile: dev   #激活文件
      uri: http://localhost:8888/  #服务端地址
server:
  port: 8881
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
